# Change these first
owner: ferdium # Your GitHub organization or username, where this repository lives
repo: ferdium-status # The name of this repository

sites:
  - name: Website
    url: https://ferdium.org
  - name: API (Server)
    url: https://api.ferdium.org
  - name: Debugger
    url: https://debug.ferdium.org
  - name: Test Broken Site
    url: https://thissitedoesnotexist.koj.co

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /ferdium-status
  logoUrl: https://raw.githubusercontent.com/ferdium/ferdium-branding/main/icon/ferdium-icon.svg
  name: Ferdium Status
  introTitle: "**Ferdium Status** shows all service status for [Ferdium](https://ferdium.org)."
  introMessage: All system status.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
